//+------------------------------------------------------------------+
//|                                    CSDKErrorCatalog.generated.mqh |
//|  AUTO-GENERATED by aws/contracts/schemas/error_catalog/generate.mjs|
//|  Source of truth: aws/contracts/schemas/error_catalog/catalog.json |
//|  Regenerate: node aws/contracts/schemas/error_catalog/generate.mjs |
//|  DO NOT EDIT BY HAND.                                             |
//+------------------------------------------------------------------+
#ifndef CSDK_ERROR_CATALOG_GENERATED_MQH
#define CSDK_ERROR_CATALOG_GENERATED_MQH

// Public docs base. Every coded message points the user at
// themarketrobo.com/problems/<code> so they can search the fix guide.
#define TMKR_PROBLEMS_BASE_URL "themarketrobo.com/problems"

// One stable code per catalog entry. Use these with TMKRUserErrorCoded()/TMKRLogCoded().
#define TMKR_ERR_1001 "TMKR-1001"  // [error] Invalid product configuration (robot version ID)
#define TMKR_ERR_1002 "TMKR-1002"  // [error] API key is required
#define TMKR_ERR_1003 "TMKR-1003"  // [error] Robot configuration class missing
#define TMKR_ERR_1004 "TMKR-1004"  // [warning] Indicator short name not set (cannot be remotely removed)
#define TMKR_ERR_1005 "TMKR-1005"  // [error] This product session was terminated
#define TMKR_ERR_1006 "TMKR-1006"  // [warning] Saved session could not be restored (started fresh)
#define TMKR_ERR_2001 "TMKR-2001"  // [error] Invalid API key
#define TMKR_ERR_2002 "TMKR-2002"  // [warning] Authentication required
#define TMKR_ERR_2003 "TMKR-2003"  // [error] Session token expired
#define TMKR_ERR_2004 "TMKR-2004"  // [error] Authentication token invalid
#define TMKR_ERR_2005 "TMKR-2005"  // [error] License expired or not yet started
#define TMKR_ERR_2006 "TMKR-2006"  // [error] License inactive
#define TMKR_ERR_2007 "TMKR-2007"  // [error] License not found
#define TMKR_ERR_2008 "TMKR-2008"  // [error] Robot version does not match the license
#define TMKR_ERR_2009 "TMKR-2009"  // [error] Submission is not in a testable state
#define TMKR_ERR_2010 "TMKR-2010"  // [error] Session does not belong to this caller
#define TMKR_ERR_3001 "TMKR-3001"  // [error] Network requests are not allowed (WebRequest not enabled)
#define TMKR_ERR_3002 "TMKR-3002"  // [error] Invalid server address
#define TMKR_ERR_3003 "TMKR-3003"  // [error] Cannot connect to the server
#define TMKR_ERR_3004 "TMKR-3004"  // [warning] Connection timed out
#define TMKR_ERR_3005 "TMKR-3005"  // [error] Connection refused
#define TMKR_ERR_3010 "TMKR-3010"  // [error] DLL imports are disabled (indicators)
#define TMKR_ERR_3011 "TMKR-3011"  // [error] Indicator network request failed (WinINet)
#define TMKR_ERR_3020 "TMKR-3020"  // [error] Could not connect to TheMarketRobo service
#define TMKR_ERR_3040 "TMKR-3040"  // [warning] Terminal not connected / account data unavailable
#define TMKR_ERR_3050 "TMKR-3050"  // [warning] Too many requests (rate limited)
#define TMKR_ERR_4001 "TMKR-4001"  // [warning] Heartbeat sequence mismatch (auto-resynced)
#define TMKR_ERR_4002 "TMKR-4002"  // [error] Connection lost — product removed after repeated heartbeat failures
#define TMKR_ERR_4003 "TMKR-4003"  // [error] Session not found or no longer active
#define TMKR_ERR_4004 "TMKR-4004"  // [error] Maximum concurrent sessions reached
#define TMKR_ERR_4005 "TMKR-4005"  // [warning] Session already ended
#define TMKR_ERR_4006 "TMKR-4006"  // [warning] A change request is already pending
#define TMKR_ERR_4007 "TMKR-4007"  // [warning] Session end request failed
#define TMKR_ERR_4008 "TMKR-4008"  // [error] Request failed validation
#define TMKR_ERR_4009 "TMKR-4009"  // [error] Invalid request format
#define TMKR_ERR_4010 "TMKR-4010"  // [error] Missing required field
#define TMKR_ERR_5001 "TMKR-5001"  // [warning] Config field rejected — invalid value
#define TMKR_ERR_5002 "TMKR-5002"  // [warning] Config field rejected — out of range
#define TMKR_ERR_5003 "TMKR-5003"  // [warning] Config field not found
#define TMKR_ERR_5004 "TMKR-5004"  // [warning] Config field is read-only
#define TMKR_ERR_5005 "TMKR-5005"  // [info] Config change feature is disabled
#define TMKR_ERR_5010 "TMKR-5010"  // [warning] Symbol not found in session
#define TMKR_ERR_5011 "TMKR-5011"  // [warning] Symbol unavailable (rejected by terminal/broker)
#define TMKR_ERR_5012 "TMKR-5012"  // [warning] Trading disabled for symbol
#define TMKR_ERR_5013 "TMKR-5013"  // [info] Symbol change feature is disabled
#define TMKR_ERR_6001 "TMKR-6001"  // [error] Session terminated by the platform
#define TMKR_ERR_6002 "TMKR-6002"  // [error] Authentication failed during refresh — product removed
#define TMKR_ERR_6003 "TMKR-6003"  // [error] Indicator could not be removed automatically
#define TMKR_ERR_6004 "TMKR-6004"  // [error] Indicator disabled by safety fallback
#define TMKR_ERR_9001 "TMKR-9001"  // [error] Internal server error
#define TMKR_ERR_9002 "TMKR-9002"  // [error] Database error
#define TMKR_ERR_9003 "TMKR-9003"  // [error] Cache error
#define TMKR_ERR_9010 "TMKR-9010"  // [error] Product could not start (internal initialization failure)

#endif
//+------------------------------------------------------------------+
