#!/usr/bin/env bash
# commit-msg — conventional-commit lint, ONE body for both hook runners.
# (ci-cd-hardening P2, eng review D12. Template: hub owns the master copy at
# scripts/templates/commit-msg.sh — THIS FILE. Every repo copies it VERBATIM (into
# <repo>/.husky/commit-msg, or <repo>/scripts/hooks/commit-msg.sh behind a shim), or wires
# it via scripts/templates/commit-msg.pre-commit.yaml for the pre-commit-framework repos.
# 🚫 Never edit a copy: edit THIS file and re-sync every copy in the same change, or the
# next verify:local gate 0 reds in whichever repo you left behind.)
#
# ── WHY THIS HOOK EXISTS AT ALL ──────────────────────────────────────────────────────
# In MQL52026 the deploy fires on green CI, and `commitlint` is one of the required
# checks — so a squash body longer than 100 columns is not a style nit, it is
# **the box never gets the deploy**, presenting as "CI was green and nothing shipped".
# That has bitten twice (local-verification.md §Traps). A commit-msg hook is the cheapest
# place to catch it: at `git commit`, before a push, before a PR, before a merge queue.
#
# ── WHY IT IS NOT `npx commitlint` ───────────────────────────────────────────────────
# Three of the eleven repos have no node toolchain at all, and an `npx` install inside a
# hook is a network round-trip on every commit. So the FAST path is pure bash — it
# catches the two rules that actually break this fleet (type-enum, body line length) in
# milliseconds — and the FULL commitlint still runs in CI and in `verify:local`. A hook
# is fast feedback, never the gate.
#
# Usage (as a hook): commit-msg <path-to-COMMIT_EDITMSG>
# Env:
#   COMMIT_MSG_TYPES  space-separated type allow-list (default: conventional + this
#                     fleet's machinery types). Override per repo, do not edit this file.
#   COMMIT_MSG_MAX    max body/footer line length (default 100 — commitlint's
#                     body-max-line-length, and the number MQL52026's deploy turns on)
#   COMMIT_MSG_HEADER_MAX  max subject length (default: COMMIT_MSG_MAX — commitlint's
#                     header-max-length, also 100)
# Exit: 0 = fine · 1 = refuse the commit

set -u

# ${#line} counts BYTES in the C/POSIX locale and CHARACTERS in a UTF-8 one, while
# commitlint's body-max-line-length counts JS string characters. Git hooks routinely
# inherit a LANG-unset environment (cron, GUI clients, CI containers), so without this
# a legal 40-character line of em-dashes is refused as "120 chars" — stricter than the
# gate this hook mirrors, which is the one direction a fast-feedback hook must not fail.
# Pin the first UTF-8 locale the system actually has; if none, fall back to byte
# counting and SAY so rather than silently changing what the number means.
if [ "$(printf '\303\251' | wc -m | tr -d " ")" != "1" ]; then
  for _loc in C.UTF-8 en_US.UTF-8 POSIX.UTF-8 en_GB.UTF-8; do
    if locale -a 2>/dev/null | grep -qxF "$_loc"; then
      LC_ALL="$_loc"; export LC_ALL; break
    fi
  done
  if [ "$(printf '\303\251' | wc -m | tr -d " ")" != "1" ]; then
    echo "commit-msg: no UTF-8 locale found — counting BYTES, so non-ASCII lines may over-count." >&2
  fi
fi

MSG_FILE="${1:-}"
[ -n "$MSG_FILE" ] && [ -f "$MSG_FILE" ] || {
  echo "commit-msg: no message file given — refusing to pretend the message is fine." >&2
  exit 1
}

MAX="${COMMIT_MSG_MAX:-100}"
# The DEFAULT vocabulary is the conventional set that `@commitlint/config-conventional` enforces
# where a repo pins no custom `type-enum`. A repo whose CI accepts MORE types must not fork this
# line — a hook that refuses what CI accepts teaches `--no-verify`, and a forked rule set is drift
# by definition (every verify:local `cmp`s this file against hub's master). Supply the extra types
# from a thin per-repo SHIM that exports COMMIT_MSG_TYPES and then execs this file; hub's own
# .githooks/commit-msg and sdk-mql5-lib's .githooks/commit-msg are the two worked examples.
TYPES="${COMMIT_MSG_TYPES:-build chore ci docs feat fix perf refactor revert style test}"

# Strip the scissors section FIRST, then git's comment lines. Order is load-bearing:
# the scissors line is itself a comment, so '/^#/d' running first deletes it and the
# range expression can never match — leaving `git commit -v`'s verbatim diff (which is
# NOT comment-prefixed) in BODY, where every source line over 100 columns is reported
# as a body-length violation. That refuses nearly every verbose commit in this repo,
# and the only escape is the --no-verify this hook calls emergency-only.
BODY="$(sed -e '/^# ------------------------ >8 /,$d' -e '/^#/d' "$MSG_FILE")"
SUBJECT="$(printf '%s\n' "$BODY" | sed -n '1p')"

# A merge/revert/fixup commit is git's own wording; linting it means refusing a merge.
case "$SUBJECT" in
  Merge\ *|Revert\ *|fixup!\ *|squash!\ *|amend!\ *) exit 0 ;;
esac
[ -n "$SUBJECT" ] || { echo "commit-msg: empty subject." >&2; exit 1; }

fail=0
say() { printf '  ✖ %s\n' "$*" >&2; fail=1; }

# 1. header shape: <type>(<scope>)!: <subject>
# `[a-z0-9-]+`, not `[a-z-]+`: a conventional type may contain digits, and at least one real
# fleet vocabulary uses one — trade-backend's CI type-enum accepts `i18n`. With the digit class
# missing, such a subject failed this SHAPE check before the allow-list was ever consulted, so
# the hook refused a type its own CI accepts and no allow-list edit could have fixed it.
if ! printf '%s' "$SUBJECT" | grep -Eq '^[a-z0-9-]+(\([^)]+\))?!?: .+'; then
  say "subject is not conventional: expected '<type>(<scope>)!: <description>'"
  say "  got: $SUBJECT"
else
  TYPE="$(printf '%s' "$SUBJECT" | sed -E 's/^([a-z0-9-]+).*/\1/')"
  ok=0
  for t in $TYPES; do [ "$t" = "$TYPE" ] && ok=1; done
  if [ "$ok" -eq 0 ]; then
    say "type '$TYPE' is not in this repo's allow-list"
    say "  allowed: $TYPES"
    say "  (override with COMMIT_MSG_TYPES; do not edit the shared template)"
  fi
fi

# 2. header length — commitlint's header-max-length, which is ALSO 100 and which the
# body loop below deliberately skips (line 1 is `continue`d). Without this the hook
# accepted a 126-character subject and CI refused it, i.e. the hook was green on the
# exact class of message it exists to stop. Squash merges make this easy to hit: the
# landed subject is the PR title plus " (#NN)", so lint the number the merge produces.
HDRMAX="${COMMIT_MSG_HEADER_MAX:-$MAX}"
# `wc -m`, not `${#…}`: husky runs this hook as `sh -e`, and dash (Debian/Ubuntu /bin/sh) has no
# multibyte support, so `${#var}` counts BYTES whatever the locale — 99 em-dashes read as 297.
SUBJECT_LEN="$(printf '%s' "$SUBJECT" | wc -m | tr -d ' ')"
if [ "$SUBJECT_LEN" -gt "$HDRMAX" ]; then
  say "subject is ${SUBJECT_LEN} chars (max $HDRMAX): $(printf '%.60s' "$SUBJECT")…"
  say "  a squash merge appends ' (#NN)' — leave room for it"
fi

# 3. body/footer line length — the rule whose failure looks like a missing deploy.
n=0
while IFS= read -r line; do
  n=$((n + 1))
  [ "$n" -eq 1 ] && continue
  # A bare URL or a fenced/indented block cannot be rewrapped; commitlint's own
  # body-max-line-length does not exempt them, so neither does this — but say which.
  LINE_LEN="$(printf '%s' "$line" | wc -m | tr -d ' ')"
  if [ "$LINE_LEN" -gt "$MAX" ]; then
    say "line $n is ${LINE_LEN} chars (max $MAX): $(printf '%.60s' "$line")…"
  fi
done <<EOF
$BODY
EOF

if [ "$fail" -ne 0 ]; then
  cat >&2 <<'HINT'

commit-msg refused this message. In MQL52026 and the other CD repos a commitlint
failure means the DEPLOY SILENTLY NEVER HAPPENS — this hook is cheaper than that.
Fix the message; re-run `git commit`. Bypass is emergency-only (`--no-verify`) and
the PR body must say why: CI runs the full commitlint and will red it anyway.
HINT
  exit 1
fi
exit 0
