#!/usr/bin/env bash
# commit-msg — conventional-commit lint, ONE body for both hook runners.
# (ci-cd-hardening P2, eng review D12. Template: hub owns the master copy at
# scripts/templates/commit-msg.sh; every repo phase copies it VERBATIM into
# <repo>/.husky/commit-msg, or wires it via scripts/templates/commit-msg.pre-commit.yaml
# for the pre-commit-framework repos.)
#
# ── WHY THIS HOOK EXISTS AT ALL ──────────────────────────────────────────────────────
# In MQL52026 the deploy fires on green CI, and `commitlint` is one of the required
# checks — so a squash body longer than 100 columns is not a style nit, it is
# **the box never gets the deploy**, presenting as "CI was green and nothing shipped".
# That has bitten twice (local-verification.md §Traps). A commit-msg hook is the cheapest
# place to catch it: at `git commit`, before a push, before a PR, before a merge queue.
#
# ── WHY IT IS NOT `npx commitlint` ───────────────────────────────────────────────────
# Three of the eleven repos have no node toolchain at all, and an `npx` install inside a
# hook is a network round-trip on every commit. So the FAST path is pure bash — it
# catches the two rules that actually break this fleet (type-enum, body line length) in
# milliseconds — and the FULL commitlint still runs in CI and in `verify:local`. A hook
# is fast feedback, never the gate.
#
# Usage (as a hook): commit-msg <path-to-COMMIT_EDITMSG>
# Env:
#   COMMIT_MSG_TYPES  space-separated type allow-list (default: conventional + this
#                     fleet's machinery types). Override per repo, do not edit this file.
#   COMMIT_MSG_MAX    max body/footer line length (default 100 — commitlint's
#                     body-max-line-length, and the number MQL52026's deploy turns on)
# Exit: 0 = fine · 1 = refuse the commit

set -u

MSG_FILE="${1:-}"
[ -n "$MSG_FILE" ] && [ -f "$MSG_FILE" ] || {
  echo "commit-msg: no message file given — refusing to pretend the message is fine." >&2
  exit 1
}

MAX="${COMMIT_MSG_MAX:-100}"
TYPES="${COMMIT_MSG_TYPES:-build chore ci docs feat fix perf refactor revert style test}"

# Strip comment lines (git's template) and the scissors section.
BODY="$(sed -e '/^#/d' -e '/^# ------------------------ >8 /,$d' "$MSG_FILE")"
SUBJECT="$(printf '%s\n' "$BODY" | sed -n '1p')"

# A merge/revert/fixup commit is git's own wording; linting it means refusing a merge.
case "$SUBJECT" in
  Merge\ *|Revert\ *|fixup!\ *|squash!\ *|amend!\ *) exit 0 ;;
esac
[ -n "$SUBJECT" ] || { echo "commit-msg: empty subject." >&2; exit 1; }

fail=0
say() { printf '  ✖ %s\n' "$*" >&2; fail=1; }

# 1. header shape: <type>(<scope>)!: <subject>
if ! printf '%s' "$SUBJECT" | grep -Eq '^[a-z-]+(\([^)]+\))?!?: .+'; then
  say "subject is not conventional: expected '<type>(<scope>)!: <description>'"
  say "  got: $SUBJECT"
else
  TYPE="$(printf '%s' "$SUBJECT" | sed -E 's/^([a-z-]+).*/\1/')"
  ok=0
  for t in $TYPES; do [ "$t" = "$TYPE" ] && ok=1; done
  if [ "$ok" -eq 0 ]; then
    say "type '$TYPE' is not in this repo's allow-list"
    say "  allowed: $TYPES"
    say "  (override with COMMIT_MSG_TYPES; do not edit the shared template)"
  fi
fi

# 2. body/footer line length — the rule whose failure looks like a missing deploy.
n=0
while IFS= read -r line; do
  n=$((n + 1))
  [ "$n" -eq 1 ] && continue
  # A bare URL or a fenced/indented block cannot be rewrapped; commitlint's own
  # body-max-line-length does not exempt them, so neither does this — but say which.
  if [ "${#line}" -gt "$MAX" ]; then
    say "line $n is ${#line} chars (max $MAX): ${line:0:60}…"
  fi
done <<EOF
$BODY
EOF

if [ "$fail" -ne 0 ]; then
  cat >&2 <<'HINT'

commit-msg refused this message. In MQL52026 and the other CD repos a commitlint
failure means the DEPLOY SILENTLY NEVER HAPPENS — this hook is cheaper than that.
Fix the message; re-run `git commit`. Bypass is emergency-only (`--no-verify`) and
the PR body must say why: CI runs the full commitlint and will red it anyway.
HINT
  exit 1
fi
exit 0
